services:
   un-redact:
    container_name: 'Un-Redact'
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    build: .
    ports:
      - 5800:5800
    labels:
       net.unraid.docker.webui: 'http://[IP]:[PORT:5800]'
       net.unraid.docker.icon: 'https://redact.dev/images/appicon.png'
